### ISSUE TITLE
Power for 4 motors

### ISSUE THREAD

**Issue by Rishan123** [andrewfell/CERC-PIWars2019#1]
With the four-wheeled chassis, 9v isn't enough to power 4 motors. So, which battery should I use?

@andrewfell @Eamonn2112 @akshsam @huntstuart

**Comment by Rishan123** [comment]
> With the four-wheeled chassis, 9v isn't enough to power 4 motors. So, which battery should I use?

 I think I solved my own problem!

**Comment by andrewfell** [comment]
Hello Rishan,

The motors work well at 9V.  You have to wire two of them in parallel circuit for the left side (which connected to one channel on the motor driver board) and then two in parallel circuit for the right side (connect these to the other channel on the motor board).

Parallel circuits: https://www.youtube.com/watch?v=Az7VRuTA8dQ

**Comment by andrewfell** [comment]
If you wire them in parallel, then each motor will get all of the 9V to it.. Then they run fast enough.
Here is our Robot using 6xAA batteries (9V), motors in parallel. https://youtu.be/u95Je9c5SPo

**Comment by andrewfell** [comment]
Make sure that when you connect them in parallel they both run the same way.. i.e. you need to wire them to that both motors run forward when you ask them to run forward.  If one motor turns opposite to the other, then swap the + and - connection to the motor that is running the wrong way.

**Comment by Rishan123** [comment]
Thanks!
